ingress:
  hosts:
    - fps.ahub.${deploy_env}.${deploy_dc}.${deploy_dns_zone}
  tls:
    clusterIssuer: adp-ca-issuer
  class: long-txn
container:
  env:
    JDK_JAVA_OPTIONS:
      > # multi-line string. INTENDATION MATTERS! See: <https://yaml-multiline.info/>
      -Dspring.config.import=configserver:http://esi-ahub-cloud-config-${deploy_env}:8080
      -Dspring.cloud.config.label=cloud-properties-${deploy_env}
      -Xms512m -Xmx1024m -Xss228k -XX:+UseZGC
volumes:
  dvts-request-share:
    mountPath: /etc/dvts/request